Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  Max: 8

Metrics/PerceivedComplexity:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  DisplayStyleGuide: true